package org.spribe.booking.model.enumeration;

public enum EventType {
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    UNIT_CREATED,
    UNIT_UPDATED,
    UNIT_DELETED,
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_EXPIRED,
    BOOKING_COMPLETED,
    PAYMENT_CREATED,
    PAYMENT_STATUS_UPDATED,
    PAYMENT_COMPLETED,
    PAYMENT_REFUNDED,
    PAYMENT_CANCELLED
} 